### PR TITLE
广式萝卜牛腩

### PR DESCRIPTION
**Pull request by HenryChou007**
美味广式萝卜牛腩做法

## 注意

Pull Request 提交后，预计 1 分钟内将会得到自动化格式检查的结果。只有通过自动化检查的 Pull Request 才会被人工审核。

- [x] 请确保此 Pull Request 能够通过自动化代码检查。

## 签署

必须签署下面的对话框才能开始审核。

### HowToCook 仓库采用了 [The Unlicense](https://unlicense.org/) 协议

菜谱在签入前，必须确保其可以**直接声明进入 "公共领域"（public domain)**。这意味着一旦合并后，任何人都**可以**自由复制，修改，发布，使用，编译，出售或以菜谱的形式或菜的形式分发，**无论**是出于**商业目的**还是**非商目的**，以及**任何**手段。

- [x] 我确保了我的内容不涉及版权内容，并且授权它 The Unlicense 协议。

### CODE REVIEW

**Comment by HenryChou007** [comment]
美味广式萝卜牛腩做法

**Comment by HenryChou007** [comment]
美味广式萝卜牛腩做法,请通过吧，后续我还会添加其它美味菜谱

**Comment by Anduin2017** [comment]
```bash
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:10: MD009 Trailing spaces
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:12: MD009 Trailing spaces
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:14: MD009 Trailing spaces
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:1[5](https://github.com/Anduin2017/HowToCook/actions/runs/8038887093/job/21955304442?pr=1307#step:5:6): MD009 Trailing spaces
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:1[7](https://github.com/Anduin2017/HowToCook/actions/runs/8038887093/job/21955304442?pr=1307#step:5:8): MD009 Trailing spaces
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:1[8](https://github.com/Anduin2017/HowToCook/actions/runs/8038887093/job/21955304442?pr=1307#step:5:9): MD00[9](https://github.com/Anduin2017/HowToCook/actions/runs/8038887093/job/21955304442?pr=1307#step:5:10) Trailing spaces
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:19: MD009 Trailing spaces
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:20: MD009 Trailing spaces
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:21: MD009 Trailing spaces
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:22: MD009 Trailing spaces
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:23: MD009 Trailing spaces
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:24: MD009 Trailing spaces
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:49: MD022 Headers should be surrounded by blank lines
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:50: MD032 Lists should be surrounded by blank lines
```

**Comment by HenryChou007** [comment]
提交pr

**Comment by HenryChou007** [comment]
格式修改

**Comment by HenryChou007** [comment]
> ```shell
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:10: MD009 Trailing spaces
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:12: MD009 Trailing spaces
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:14: MD009 Trailing spaces
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:1[5](https://github.com/Anduin2017/HowToCook/actions/runs/8038887093/job/21955304442?pr=1307#step:5:6): MD009 Trailing spaces
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:1[7](https://github.com/Anduin2017/HowToCook/actions/runs/8038887093/job/21955304442?pr=1307#step:5:8): MD009 Trailing spaces
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:1[8](https://github.com/Anduin2017/HowToCook/actions/runs/8038887093/job/21955304442?pr=1307#step:5:9): MD00[9](https://github.com/Anduin2017/HowToCook/actions/runs/8038887093/job/21955304442?pr=1307#step:5:10) Trailing spaces
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:19: MD009 Trailing spaces
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:20: MD009 Trailing spaces
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:21: MD009 Trailing spaces
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:22: MD009 Trailing spaces
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:23: MD009 Trailing spaces
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:24: MD009 Trailing spaces
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:49: MD022 Headers should be surrounded by blank lines
> ./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:50: MD032 Lists should be surrounded by blank lines
> ```

已经处理完成~

**Comment by Anduin2017** [comment]
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:49: MD022 Headers should be surrounded by blank lines
./dishes/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md:[5](https://github.com/Anduin2017/HowToCook/actions/runs/8107732636/job/22159733623?pr=1307#step:5:6)0: MD032 Lists should be surrounded by blank lines

**Comment by AsenHu** [comment]
@HenryChou007 已经合并进主分支 https://github.com/Anduin2017/HowToCook/commit/68ff5cfd5531908acb3793890fee80b4459d8e28 可以 close 了

**Pull request closed without merging**
